name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run tscheck
      - name: Lint web
        run: npm run lint:web
      - name: Unit tests
        run: npm test -- --run
